---
title: "Risk Management with R - Module 1 - Data and Returns"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: inline
---

The code from the course was adapted using the [**tidyquant**](https://business-science.github.io/tidyquant/index.html) package as a way to better understand its workflow and functions. 

## Libraries

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(quantmod)
library(tidyquant)
```


## 1. Retrieving data fom FRED

```{r}

#security = "GOLDPMGBD228NLBM"

security = "WILL5000IND"

wilsh <- tq_get(security, get = "economic.data", from = "1979-12-31", to  = "2017-12-31")

wilsh <- wilsh %>% 
  na.omit()

head(wilsh, 3)
tail(wilsh, 3)

wilsh %>% 
  ggplot(aes(x = date, y = price)) +
  geom_line() +
  labs(title = "WILL 5000 Indext") + 
  theme_tq()

```

## 2. Daily Returns

```{r}
returns <- diff(log(wilsh$price))

returns <- append(returns, 0, 0)

wilsh <- wilsh %>% 
  mutate(logret = NA)

wilsh$logret = returns

#removing first row
wilsh <- wilsh[-1,]

wilsh %>% 
  ggplot(aes(x = date, y = logret)) +
  geom_line() +
  labs(title = "WILL 5000 Indext", y = "Log Returns") + 
  theme_tq()
```

Or using the function:

```{r}

log_returns <- wilsh %>%
    group_by(symbol) %>%
    tq_transmute(select = price, 
                 mutate_fun = periodReturn, 
                 period     = "daily", 
                 col_rename = "log_return")

```


## 3. Longer Returns

### 3.1 Weekly returns

period_return = exp(log_ret_1 + logret2_ + ..... logret_n) - 1

n: days in period

```{r}

w_returns <- wilsh %>%
    group_by(symbol) %>%
    tq_transmute(select = price, 
                 mutate_fun = periodReturn, 
                 period     = "weekly", 
                 col_rename = "w_return")

w_returns %>% 
  ggplot(aes(x = date, y = w_return)) +
  geom_line() +
  labs(title = "WILL 5000 Indext", y = "Weekly Returns") + 
  theme_tq()

```

### 3.2 Annual returns
```{r}

y_returns <- wilsh %>%
    group_by(symbol) %>%
    tq_transmute(select = price, 
                 mutate_fun = periodReturn, 
                 period     = "yearly", 
                 col_rename = "y_return")

y_returns %>% 
  ggplot(aes(x = date, y = y_return)) +
  geom_line() +
  labs(title = "WILL 5000 Indext", y = "Yearly Returns") + 
  theme_tq()

```


## 4. Application 1

```{r}


yen <- tq_get("DEXJPUS", get = "economic.data", from = "1979-12-31", to  = "2017-12-31")

yen <- yen %>% 
  na.omit()

yen$price <- 1/yen$price

yen %>% 
  ggplot(aes(x = date, y = price)) +
  geom_line() +
  theme_tq()

d_returns <- yen %>%
    group_by(symbol) %>%
    tq_transmute(select = price, 
                 mutate_fun = periodReturn, 
                 period     = "daily", 
                 col_rename = "d_return")

m_returns <- yen %>%
    group_by(symbol) %>%
    tq_transmute(select = price, 
                 mutate_fun = periodReturn, 
                 period     = "monthly", 
                 col_rename = "m_return")

exp(m_returns$m_return[2]) - 1


q_returns <- yen %>%
    group_by(symbol) %>%
    tq_transmute(select = price, 
                 mutate_fun = periodReturn, 
                 period     = "quarterly", 
                 col_rename = "q_return")

tail(q_returns,3)


y_returns <- yen %>%
    group_by(symbol) %>%
    tq_transmute(select = price, 
                 mutate_fun = periodReturn, 
                 period     = "yearly", 
                 col_rename = "y_return")


tail(y_returns,3)

exp(y_returns$y_return[39]) - 1

```
